apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ambulance-app
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: U2lkQDk4OTc=
  DB_HOST: bXlzcWwtc3Zj
  DB_NAME: YW1idWxhbmNl
  GROQ_API_KEY: Z3NrX0dRakRYRHlaVDJKNnU0amcxMTZZV0dkeWIzRllXU0duNnRBMmlJNkpqSTBzWGdLMEszdmI=
