apiVersion: v1
kind: Service
metadata:
  name: ambulance-app-service
  namespace: ambulance-app
  labels:
    app: ambulance-app
spec:
  type: NodePort
  selector:
    app: ambulance-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 32000
